import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { SystemData } from './systemHandler';

export interface SystemState {
  status: 'idle' | 'loading' | 'failed';
  data?: SystemData;
}

const initialState: SystemState = {
  status: 'idle'
};

export const getSystemData = createAsyncThunk('system/get', async () => {
  return await window.electron.system();
});

export const systemSlice = createSlice({
  name: 'system',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getSystemData.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getSystemData.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload;
      })
      .addCase(getSystemData.rejected, (state) => {
        state.status = 'failed';
      });
  }
});

export default systemSlice.reducer;
