export const NETWORK_URL = '/network';

export const NETWORK_INTERFACES_INVOKE = 'NETWORK_INTERFACES_INVOKE';
export const NETWORK_STATS_INVOKE = 'NETWORK_STATS_INVOKE';
export const NETWORK_CONNECTIONS_INVOKE = 'NETWORK_CONNECTIONS_INVOKE';
