import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { OsData } from './osHandler';

export interface OsState {
  status: 'idle' | 'loading' | 'failed';
  data?: OsData;
}

const initialState: OsState = {
  status: 'idle'
};

export const getOsData = createAsyncThunk('os/osinfo', async () => {
  return await window.electron.os_info();
});

export const osSlice = createSlice({
  name: 'os',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getOsData.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getOsData.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload;
      })
      .addCase(getOsData.rejected, (state) => {
        state.status = 'failed';
      });
  }
});

export default osSlice.reducer;
